In [6]:
import requests
import json
import random
import sklearn
import csv
import os
import time
import sqlalchemy
import pandas
import pickle
import numpy as np
from datetime import datetime, timedelta
import geopy
import nltk
from geopy.distance import vincenty
# from sshtunnel import SSHTunnelForwarder #Run pip install sshtunnel
from sqlalchemy.orm import sessionmaker #Run pip install sqlalchemy
from sklearn.preprocessing import MinMaxScaler, StandardScaler

import settings as s
import load_dataset
import preprocessing_gps

os.chdir('src')

np.random.seed(7)
random.seed(7)

EXPERIMENT_PARAMETERS = s.EXPERIMENT_PARAMETERS
FIGURE_DIR = s.FIGURE_DIR
X_GRID_FILE = s.X_GRID_FILE
Y_GRID_FILE = s.Y_GRID_FILE
Y_FILE_PREDICTED_LSTM = s.Y_FILE_PREDICTED_LSTM
Y_FILE_PREDICTED_VELOCITY = s.Y_FILE_PREDICTED_VELOCITY

MODEL_FILE_LSTM_GRID = s.MODEL_FILE_LSTM_GRID
MODEL_WEIGHT_FILE_LSTM_GRID = s.MODEL_WEIGHT_FILE_LSTM_GRID

GEOJSON_FILE_OBSERVATION_GRID = s.GEOJSON_FILE_OBSERVATION_GRID
GEOJSON_FILE_TRUE_GRID = s.GEOJSON_FILE_TRUE_GRID
GEOJSON_FILE_PREDICTED_LSTM_GRID = s.GEOJSON_FILE_PREDICTED_LSTM_GRID



In [16]:
X = np.load(X_GRID_FILE)
Y = np.load(Y_GRID_FILE)

print(X.shape)
print(Y.shape)



(488, 144, 1)
(488, 6, 1)


In [3]:
df_all_users.dtypes

uid                   object
time_start    datetime64[ns]
time_end      datetime64[ns]
x                    float64
y                    float64
mode                  object
dtype: object

In [5]:
len(target_row)

NameError: name 'target_row' is not defined

In [41]:
temporal_index

[[0, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 0)],
 [1, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 5)],
 [2, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 10)],
 [3, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 15)],
 [4, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 20)],
 [5, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 25)],
 [6, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 30)],
 [7, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 35)],
 [8, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 40)],
 [9, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 45)],
 [10, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 50)],
 [11, 2012, 30, 3, datetime.datetime(2012, 7, 25, 0, 55)],
 [12, 2012, 30, 3, datetime.datetime(2012, 7, 25, 1, 0)],
 [13, 2012, 30, 3, datetime.datetime(2012, 7, 25, 1, 5)],
 [14, 2012, 30, 3, datetime.datetime(2012, 7, 25, 1, 10)],
 [15, 2012, 30, 3, datetime.datetime(2012, 7, 25, 1, 15)],
 [16, 2012, 30, 3, datetime.datetime(2012, 7, 25, 1, 20)],
 [17, 2012,

In [9]:
def convert_raw_coordinates_to_spatial_index(EXPERIMENT_PARAMETERS, spatial_index, x, y):
    x_index = int((x - EXPERIMENT_PARAMETERS["AOI"][0]) // spatial_index[0])
    y_index = int((y - EXPERIMENT_PARAMETERS["AOI"][1]) // spatial_index[1])
    # print(x_index)
    # print(y_index)
    spatial_index_number = x_index + (spatial_index[3] * y_index)
    return spatial_index_number

In [20]:
for name, group in grouped:
    traj = []
    if num_user == 0:
        break
    else:
        # print(name)
        # print(group)
        # For each user and each temporal index, find a location and mode to make regualized file
        for t_index in temporal_index:
            target_time = t_index[4]
            target_row = group.loc[(group['time_start'] <= target_time) & (group['time_end'] >= target_time)]
            if (len(target_row) > 0):
                x = target_row.at['x']
                y = target_row.at['y']
                mode = target_row.at['mode']
                s_index = convert_raw_coordinates_to_spatial_index(EXPERIMENT_PARAMETERS, spatial_index, x, y)
                traj.append([name, t_index[0], x, y, mode, s_index])
        df_user_regularized = pandas.DataFrame.from_records(traj, columns=headers)
#         print(df_user_regularized)
        df_users_regularized = df_users_regularized.append(df_user_regularized)
        num_user -= 1
# print(df_users_regularized)

array([[  35.83439243,  138.97597443],
       [  35.82211421,  139.0025391 ]])

array([[-0.01227822,  0.02656467]])

In [20]:
means = numpy.mean(diffs, axis=0)
means

array([-0.01227822,  0.02656467])

In [26]:
last = X_test[0, -1, -2:]
last

array([  35.82211421,  139.0025391 ])

In [35]:
numpy.add(last_diff, last)

array([[  35.80983599,  139.02910377]])

In [29]:
y_test[0]

array([  35.80983599,  139.02910377])

In [40]:
x_two_step = X_test[:, -2:, -2:]
x_two_step

array([[[  35.83439243,  138.97597443],
        [  35.82211421,  139.0025391 ]],

       [[  35.64696784,  139.53012587],
        [  35.64826051,  139.53204177]],

       [[  35.56753905,  139.7293991 ],
        [  35.5746431 ,  139.73400672]],

       ..., 
       [[  35.58541198,  139.7480611 ],
        [  35.58525307,  139.74703865]],

       [[  35.62086167,  139.71916685],
        [  35.62211741,  139.7202787 ]],

       [[  35.74634982,  139.72499071],
        [  35.74519885,  139.72670361]]])

In [42]:
last_diff = numpy.diff(x_two_step, axis=1)
last_diff

array([[[-0.01227822,  0.02656467]],

       [[ 0.00129267,  0.0019159 ]],

       [[ 0.00710406,  0.00460762]],

       ..., 
       [[-0.00015891, -0.00102245]],

       [[ 0.00125574,  0.00111185]],

       [[-0.00115097,  0.00171289]]])

In [48]:
last = X_test[:, -1:, -2:]
# last
prediction = numpy.add(last_diff, last)
prediction.shape

(1205, 1, 2)

In [51]:
prediction_shape = prediction.shape
prediction =prediction.reshape(prediction_shape[0], prediction_shape[2])
prediction

array([[  35.80983599,  139.02910377],
       [  35.64955318,  139.53395767],
       [  35.58174716,  139.73861433],
       ..., 
       [  35.58509415,  139.74601619],
       [  35.62337314,  139.72139055],
       [  35.74404788,  139.7284165 ]])

In [47]:
y_test

array([[  35.80983599,  139.02910377],
       [  35.64954332,  139.53396828],
       [  35.58246042,  139.73640138],
       ..., 
       [  35.58496666,  139.74602346],
       [  35.62358498,  139.72103667],
       [  35.74384336,  139.72816329]])